In [1]:
from numpy.random import rand
from numpy import transpose
import numpy as np
from time import time

In [2]:
rand(2,3)

array([[ 0.12794295,  0.7336931 ,  0.49332107],
       [ 0.16035886,  0.37012869,  0.49527613]])

In [3]:
def gen_random(Params):
    """generate a numpy binary matrix where column i is IID binary 
    with probability P[i] and has length n"""
    P,n=Params
    m=P.shape[0]
    R=rand(m,n)
    B=1*(R<P)
    return B

In [4]:
n=10
P=np.array([np.arange(0.4,0.61,0.1),]).transpose()
B=gen_random((P,n))


In [5]:
B

array([[1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 1, 0, 0]])

In [6]:
# define the P[i]'s to in the range from 0.4 to 0.6
P=np.array([np.arange(0.4,0.61,0.01),]).transpose()
n=100000
#[(P,n)]*10

In [7]:
start=time()
Params=sc.parallelize([(P,n)]*2).repartition(2)
print Params.getNumPartitions()
print time()-start

2
0.784049987793


In [8]:
start=time()
B=Params.map(gen_random).cache()
print B.count()
print 'time=',time()-start

2
time= 2.26424598694


In [9]:
i=0
j=1000
def Count(B):
    return B[:,i:j].sum(axis=1)
    

In [10]:
j=n/10
start=time()
O=B.map(Count).collect()
print 'time=',time()-start

time= 0.447887897491


In [12]:
O=np.stack(O)
O.shape

AttributeError: 'module' object has no attribute 'stack'

In [37]:
O

array([[4036, 4059, 4183, 4325, 4381, 4554, 4614, 4736, 4843, 4925, 5029,
        5135, 5269, 5305, 5419, 5534, 5647, 5788, 5804, 5854, 6039],
       [3983, 4068, 4109, 4210, 4386, 4470, 4476, 4706, 4735, 4912, 5111,
        5065, 5158, 5349, 5316, 5384, 5638, 5701, 5765, 5879, 6037]])

In [40]:
O>(j/2)

array([[False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]], dtype=bool)